# Generated by Django 3.2.9 on 2022-01-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='image',
            field=models.ImageField(default=1, upload_to='workers', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
