# Generated by Django 3.2.9 on 2022-01-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_worker_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='short_description',
            field=models.CharField(default=1, max_length=500, verbose_name='Short description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name_Surname'),
        ),
    ]
