# Generated by Django 3.2.9 on 2022-01-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_auto_20220130_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='icons',
            field=models.CharField(default=1, max_length=50, verbose_name='Icons'),
            preserve_default=False,
        ),
    ]
