# Generated by Django 3.2.9 on 2022-01-31 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_section_icons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Author')),
                ('comment', models.TextField(verbose_name='Comment')),
            ],
        ),
        migrations.AlterField(
            model_name='worker',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='sections.section', verbose_name='Sections'),
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('main_image', models.ImageField(upload_to='works', verbose_name='Main Image')),
                ('description', models.TextField(verbose_name='Description')),
                ('likes', models.IntegerField(verbose_name='Likes')),
                ('views', models.IntegerField(verbose_name='Views')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.section', verbose_name='Section')),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('image', models.ImageField(upload_to='works', verbose_name='Image')),
                ('works', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.works', verbose_name='Works')),
            ],
        ),
    ]
