# Generated by Django 3.2.9 on 2022-01-31 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0005_auto_20220131_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='works',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='sections.section', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='works',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
    ]
